version: 2.1
executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            chmod +x gradlew
            chmod +x /home/circleci/project/src/test/resources/drivers/chromedriver
            chmod +x /home/circleci/project/src/test/resources/drivers/geckodriver
      - run:
          name: Run Selenium Tests
          command: ./gradlew clean test
      - store_artifacts:
          path: test-output/HtmlReport
          destination: extent-reports
      - store_test_results:
          path: test-output/HtmlReport

workflows:
  version: 2
  build-test:
    jobs:
      - build
